---
- name: "Cleaning existing MQ packages"
  shell: 
    cmd: 'rpm -qa | grep "\-U" | xargs rpm -ev'
    warn: no
  register: uninstall_status
  changed_when: false
  when: user_action == "Uninstall" and  isOldFix.rc == 0

- name: Cleaning existing MQ packages 
  shell: 
    cmd: 'rpm -qa | grep MQSeries | xargs rpm -ev'
    warn: no
  register: uninstall_status
  changed_when: false
  when: user_action == "Uninstall" and isOldFix.rc != 0 

- name: Cleaning existing MQ packages
  shell:
    cmd: 'rpm -qa | grep MQSeries | xargs rpm -ev'
    warn: no
  register: uninstall_status
  changed_when: false
  when: user_action == 'Install' and installType == "Upgrade"
