---
# tasks file for ansible-ibmmq-deployment

- name: check if version is within acceptable range
  assert:
    that:
      - mq_target_version <= "9.2.5.0" 
      - mq_target_version >= "7.5.0.0"

- name: Verifying the given Version contains Base or fix
  local_action:
    module: shell
    cmd: "tar -tzf {{ mq_tar_location }} | grep 'MQServer/mqlicense.sh'"
    warn: false
  register: isBase
  become: false
  ignore_errors: yes
  when: user_action != 'Uninstall'

- name: Gathering MQ facts
  import_tasks: gather_facts.yml

- pause:
    minutes: 5

- name: Installing MQ
  import_tasks: install_packages.yml
  when: user_action == "Install" and installType == "NewInstall" and isBase.rc == 0

- block:
  - name: Taking backups
    import_tasks: take_backups.yml

  - name: stopping services
    import_tasks: stop_services.yml

  - name: Cleaning old packages
    import_tasks: clean_packages.yml

  - name: Installing MQ
    import_tasks: install_packages.yml

#  - name: Start Services
#    import_tasks: start_services.yml
  when: user_action == 'Install' and packageCount.stdout != "0"

- block:
  - name: Taking backups
    import_tasks: take_backups.yml

  - name: stopping services
    import_tasks: stop_services.yml
  
  - name: Cleaning packages
    import_tasks: clean_packages.yml
  when: user_action == 'Uninstall' and packageCount.stdout != "0" 
