---
- name: starting StandaloneQmgrs
  shell:
    cmd: "strmqm {{ item }}"
    warn: no
  become_user: mqm
  with_items:
    - "{{ standAloneQmgrList.stdout_lines }}"
  when: standAloneQmgrList.stdout_lines | length > 0

- name: starting MultiInstanceQmgrs
  shell:
    cmd: "strmqm -x {{ item }}"
    warn: no
  become_user: mqm
  with_items:
    - "{{ multiInstanceQmgrList.stdout_lines }}"
  when: multiInstanceQmgrList.stdout_lines | length > 0

- name: starting IIB
  shell:
    cmd: "source {{ iib_install_path }}/server/bin/mqsiprofile;mqsistart {{ item }}"
    warn: no
  become_user: "{{ iibAdminUser.stdout }}"
  with_items:
    - "{{ nodeList.stdout_lines }}"
  when: bipCount.stdout != "0" and isProfileFound.stat.exists == true and nodeList.stdout_lines | length > 0 
