---
- block:
  - name: Ending IIB process if any
    shell:
      cmd: "source {{ iib_install_path }}/server/bin/mqsiprofile;mqsistop {{ item }}"
      warn: no
    become_user: "{{ iibAdminUser }}"
    with_items:
      - "{{ nodeList.stdout_lines }}"

  - name: Wait for IIB processes to stop if any
    shell: "ps -ef | grep -i bip | grep -v pts | wc -l"
    become_user: "{{ iibAdminUser }}"
    register: iibProcCount
    changed_when: false
    until: iibProcCount.stdout == "0"
    retries: 30
    delay: 10
  when: bipCount.stdout != "0" and isProfileFound.stat.exists == true and nodeList.stdout_lines | length > 0

- name: Ending MQ Queue managers if any running
  shell:
    cmd: "{{ mq_binary_path }}/endmqm {{ item }}"
    warn: no
  become_user: mqm
  with_items:
    - "{{ standAloneQmgrList.stdout_lines }}"
    - "{{ multiInstanceQmgrList.stdout_lines }}"
  when: standAloneQmgrList.stdout_lines | length > 0 or multiInstanceQmgrList.stdout_lines | length > 0

- name: Wait for MQ processes to stop if any
  shell: "ps -ef | grep -v pts | grep -i mqm | wc -l"
  become_user: mqm
  register: mqProcCount
  changed_when: false
  until: mqProcCount.stdout == "0"
  retries: 30
  delay: 10

