##################################################################################
#  Example inputs from user
#                                                                              
#  mq_target_version: 8.0.0.14                                                   
#  mq_tar_location: /sort/ibmmq/8.0.0.14/8.0.0-WS-MQ-LinuxX64-FP0014.tar.gz
#  iib_install_path: /opt/ibm/iib-10.0.0.19
#  iibAdminUser: iibadmin
#  user_action: Install
#
#################################################################################

---
- hosts: mqservers 
  gather_facts: false
  user: root
  become: yes
  roles: 
    - role: ibmmq-deployment
      
